### ISSUE TITLE
Blocking 3rd party script in head

### ISSUE THREAD

**Issue by niutech** [wintermute-cell/magick.css#13]
Please move the blocking 3rd party `<script src="https://unpkg.com/htmx.org@1.9.11"></script>` from `<head>` to just before `</body>` for performance reasons.

**Comment by Emmanuelbinen** [comment]
Hello,
I am writing to notify that I have done it.

**Comment by wintermute-cell** [comment]
fixed with 66b6ab183032fd5fc8125fe26122096f0b6b884f
