### ISSUE TITLE
Page header overlaps when it goes to multiple lines on smaller viewports

### ISSUE THREAD

**Issue by timvdalen** [wintermute-cell/magick.css#6]
If the page title is long enough to go to multiple lines, those lines overlap:

![image](https://github.com/wintermute-cell/magick.css/assets/1038428/627caece-79d6-4eef-bcdf-6932d1d59253)

Setting `header h1`'s `line-height` to `100%` fixes the issue, but I'm not sure what your intention behind the smaller value was.

---

Thanks for making this, it looks awesome!

**Comment by wintermute-cell** [comment]
No sane intention behind that, fixed with 303cd27e4e9faf8a7e3adde07f115b691fcce37f, thanks!
