### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by amatiasq** [wintermute-cell/magick.css#9]
Hey! I love this and would like to use it on my website, thanks for publishing it.

Is there a recommended way to add syntax highlighting?

I'm currently using [highlight.js](https://highlightjs.org/) through markdown with `rehype-highlight`.

**Comment by wintermute-cell** [comment]
Hey! :)

I don't have a recommendation on this topic; I had looked into CSS only syntax highlighting, wanting to add syntax highlighting to magic.css, but it's not really a good solution. Beyond that, I think any JS solution is probably fine, so stick to your current setup if it works for you!
